import { createPortraitExtension } from './portrait-registry.ts';
import { assertValidPortraitExtension } from './portrait-validation.ts';
import { parseCommunityManifestCollection } from '../works/manifest-validator.ts';
import type {
  GalleryId,
  WorkManifest,
  WorkManifestV1,
  WorkManifestV2,
  WorkParameter,
  WorkPreset,
} from './types.ts';

export const galleries: Array<{ id: GalleryId; label: string; description: string }> = [
  {
    id: 'motion-chaos',
    label: 'Motion & Chaos',
    description: 'Order, instability, synchronization, and the geometry of motion.',
  },
  {
    id: 'matter-pattern',
    label: 'Matter & Pattern',
    description: 'How fields, phases, and local rules become visible structure.',
  },
  {
    id: 'life-reaction',
    label: 'Life & Reaction',
    description: 'Competition, excitation, infection, and chemical rhythm.',
  },
  {
    id: 'earth-climate',
    label: 'Earth & Climate',
    description: 'Feedbacks that move oceans, atmospheres, and planetary temperature.',
  },
  {
    id: 'cosmos-gravity',
    label: 'Cosmos & Gravity',
    description: 'Orbits, expansion, transit, and the choreography of gravity.',
  },
];

const parameter = (
  id: string,
  label: string,
  symbol: string,
  min: number,
  max: number,
  step: number,
  value: number,
): WorkParameter => ({ id, label, symbol, min, max, step, default: value });

const presets = (a: Record<string, number>, b: Record<string, number>): WorkPreset[] => [
  { id: 'canonical', label: 'Canonical', values: {} },
  { id: 'quiet', label: 'Quiet regime', values: a },
  { id: 'threshold', label: 'Near threshold', values: b },
];

type WorkSeed = Omit<WorkManifestV1, 'schemaVersion' | 'presets' | 'citations'> & {
  quiet: Record<string, number>;
  threshold: Record<string, number>;
  citation: [string, string];
};

const defineWork = (seed: WorkSeed): WorkManifestV2 => {
  const workPresets = presets(seed.quiet, seed.threshold);
  const portrait = createPortraitExtension({
    slug: seed.slug,
    kernel: seed.kernel,
    render: seed.render,
    parameters: seed.parameters,
    presets: workPresets,
  });
  assertValidPortraitExtension(portrait);
  return {
    schemaVersion: 2,
    slug: seed.slug,
    title: seed.title,
    subtitle: seed.subtitle,
    gallery: seed.gallery,
    runtime: seed.runtime,
    render: seed.render,
    kernel: seed.kernel,
    tier: seed.tier,
    year: seed.year,
    authors: seed.authors,
    summary: seed.summary,
    question: seed.question,
    equation: seed.equation,
    duration: seed.duration,
    parameters: seed.parameters,
    presets: workPresets,
    citations: [{ label: seed.citation[0], url: seed.citation[1] }],
    portrait,
  };
};

const builtInWorks: WorkManifestV2[] = [
  defineWork({
    slug: 'double-pendulum',
    title: 'Double Pendulum',
    subtitle: 'A hinge that forgets its future',
    gallery: 'motion-chaos',
    runtime: 'ode-v1',
    render: 'orbit',
    kernel: 'double-pendulum',
    tier: 'flagship',
    year: '1746',
    authors: ['Daniel Bernoulli'],
    duration: 30,
    summary:
      'Two coupled arms turn a simple gravitational law into an exquisitely sensitive trajectory.',
    question: 'How long can two almost identical releases remain recognizably alike?',
    equation: 'M(q)q̈ + C(q,q̇)q̇ + G(q) = 0',
    parameters: [
      parameter('gravity', 'Gravity', 'g', 2, 18, 0.1, 9.81),
      parameter('offset', 'Initial offset', 'Δθ', 0.01, 0.8, 0.01, 0.18),
    ],
    quiet: { offset: 0.04 },
    threshold: { offset: 0.42 },
    citation: [
      'Stachowiak & Okada, A numerical analysis of chaos in the double pendulum',
      'https://doi.org/10.1016/j.chaos.2006.03.056',
    ],
  }),
  defineWork({
    slug: 'kuramoto-oscillators',
    title: 'Kuramoto Oscillators',
    subtitle: 'Many clocks finding one pulse',
    gallery: 'motion-chaos',
    runtime: 'ode-v1',
    render: 'orbit',
    kernel: 'kuramoto',
    tier: 'flagship',
    year: '1975',
    authors: ['Yoshiki Kuramoto'],
    duration: 24,
    summary: 'A population of unequal oscillators crosses from incoherence into collective rhythm.',
    question: 'At what coupling strength does a crowd acquire a common time?',
    equation: 'θ̇ᵢ = ωᵢ + K/N Σ sin(θⱼ−θᵢ)',
    parameters: [
      parameter('coupling', 'Coupling', 'K', 0, 4, 0.02, 1.8),
      parameter('spread', 'Frequency spread', 'σ', 0.1, 2, 0.02, 0.8),
    ],
    quiet: { coupling: 0.4 },
    threshold: { coupling: 1.55 },
    citation: [
      'Kuramoto, Self-entrainment of a population of coupled non-linear oscillators',
      'https://doi.org/10.1007/BFb0013365',
    ],
  }),
  defineWork({
    slug: 'fput-chain',
    title: 'FPUT Chain',
    subtitle: 'The recurrence that surprised computation',
    gallery: 'motion-chaos',
    runtime: 'ode-v1',
    render: 'series',
    kernel: 'fput',
    tier: 'collection',
    year: '1955',
    authors: ['Enrico Fermi', 'John Pasta', 'Stanislaw Ulam', 'Mary Tsingou'],
    duration: 40,
    summary: 'Energy placed in one mode of a nonlinear chain disperses, then unexpectedly returns.',
    question: 'Why does a many-body system refuse to thermalize as quickly as expected?',
    equation: 'ẍᵢ = (xᵢ₊₁−2xᵢ+xᵢ₋₁) + α[(Δxᵢ₊₁)²−(Δxᵢ)²]',
    parameters: [
      parameter('alpha', 'Nonlinearity', 'α', 0, 1, 0.01, 0.25),
      parameter('amplitude', 'Excitation', 'A', 0.1, 1.5, 0.01, 0.8),
    ],
    quiet: { alpha: 0.05 },
    threshold: { alpha: 0.65 },
    citation: ['Los Alamos report LA-1940', 'https://doi.org/10.2172/4376203'],
  }),
  defineWork({
    slug: 'logistic-map',
    title: 'Logistic Map',
    subtitle: 'Infinity folded into one line',
    gallery: 'motion-chaos',
    runtime: 'discrete-v1',
    render: 'series',
    kernel: 'logistic',
    tier: 'collection',
    year: '1976',
    authors: ['Robert May'],
    duration: 80,
    summary:
      'A one-line population rule passes through stability, doubling, and deterministic chaos.',
    question: 'How can an equation with no randomness become unpredictable?',
    equation: 'xₙ₊₁ = r xₙ(1−xₙ)',
    parameters: [
      parameter('growth', 'Growth', 'r', 2.5, 4, 0.001, 3.72),
      parameter('initial', 'Initial fraction', 'x₀', 0.02, 0.98, 0.01, 0.21),
    ],
    quiet: { growth: 2.9 },
    threshold: { growth: 3.569 },
    citation: [
      'May, Simple mathematical models with very complicated dynamics',
      'https://doi.org/10.1038/261459a0',
    ],
  }),
  defineWork({
    slug: 'wave-equation',
    title: 'Wave Equation',
    subtitle: 'A shape carried without being carried away',
    gallery: 'motion-chaos',
    runtime: 'field-v1',
    render: 'field',
    kernel: 'wave',
    tier: 'collection',
    year: '1747',
    authors: ["Jean le Rond d'Alembert"],
    duration: 18,
    summary:
      'Disturbances propagate through a continuous medium while local material only oscillates.',
    question: 'What travels when the medium itself stays near home?',
    equation: '∂²u/∂t² = c²∇²u',
    parameters: [
      parameter('speed', 'Wave speed', 'c', 0.2, 2, 0.01, 1),
      parameter('mode', 'Mode mixture', 'm', 1, 6, 1, 2),
    ],
    quiet: { speed: 0.45, mode: 1 },
    threshold: { speed: 1.65, mode: 5 },
    citation: [
      "d'Alembert, Recherches sur la courbe que forme une corde tenduë mise en vibration",
      'https://epiphymaths.univ-fcomte.fr/1t1m/d_alembert-recherches_sur_la_courbe_que_forme_une_corde_tendue_mise_en_vibration-1747.pdf',
    ],
  }),
  defineWork({
    slug: 'standard-map',
    title: 'Standard Map',
    subtitle: 'Islands of order in a chaotic sea',
    gallery: 'motion-chaos',
    runtime: 'discrete-v1',
    render: 'phase',
    kernel: 'standard-map',
    tier: 'collection',
    year: '1969',
    authors: ['Boris Chirikov'],
    duration: 90,
    summary:
      'A kicked rotor reveals invariant curves, resonant islands, and global chaos in one plane.',
    question: 'Where does regular motion survive after chaos arrives?',
    equation: 'pₙ₊₁=(pₙ+K sinθₙ) mod 2π; θₙ₊₁=(θₙ+pₙ₊₁) mod 2π',
    parameters: [
      parameter('kick', 'Kick strength', 'K', 0, 7, 0.01, 1.1),
      parameter('momentum', 'Initial momentum', 'p₀', 0, 6.28, 0.01, 0.4),
    ],
    quiet: { kick: 0.35 },
    threshold: { kick: 0.9716 },
    citation: [
      'Chirikov, A universal instability of many-dimensional oscillator systems',
      'https://doi.org/10.1016/0550-3213(79)90035-X',
    ],
  }),
  defineWork({
    slug: 'fed-reaction-chain',
    title: 'Fed Reaction Chain',
    subtitle: 'Matter moving through delay',
    gallery: 'matter-pattern',
    runtime: 'reaction-network-v1',
    render: 'series',
    kernel: 'reaction-chain',
    tier: 'flagship',
    year: '1864 / curated 2026',
    authors: ['Cato Guldberg', 'Peter Waage', 'DynaMusium contributors'],
    duration: 60,
    summary:
      'A driven sequence of conversions makes lag, accumulation, and throughput visible at once.',
    question: 'How does a changing input echo through a chain of finite rates?',
    equation: 'F(t)=F[0.78+0.22 sin(2πt/18)]; Ȧ=F(t)−kA; Ḃ=kA−0.72kB; Ċ=0.72kB−0.48kC; Ṙ=0.48kC',
    parameters: [
      parameter('feed', 'Feed rate', 'F', 0.1, 2.5, 0.01, 1.05),
      parameter('rate', 'Transfer rate', 'k', 0.05, 1.2, 0.01, 0.42),
    ],
    quiet: { feed: 0.35, rate: 0.2 },
    threshold: { feed: 1.8, rate: 0.75 },
    citation: ['IUPAC Gold Book, mass action, law of', 'https://doi.org/10.1351/goldbook.08184'],
  }),
  defineWork({
    slug: 'gray-scott',
    title: 'Gray–Scott Pattern',
    subtitle: 'Spots born from reaction and diffusion',
    gallery: 'matter-pattern',
    runtime: 'field-v1',
    render: 'field',
    kernel: 'gray-scott',
    tier: 'collection',
    year: '1983',
    authors: ['Peter Gray', 'Stephen Scott'],
    duration: 20,
    summary:
      'Two diffusing chemicals sustain splitting spots, stripes, and self-replicating structures.',
    question: 'How can smoothing diffusion help create sharp pattern?',
    equation: '∂u=Dᵤ∇²u−uv²+f(1−u); ∂v=Dᵥ∇²v+uv²−(f+k)v',
    parameters: [
      parameter('feed', 'Feed', 'f', 0.01, 0.08, 0.001, 0.0367),
      parameter('kill', 'Kill', 'k', 0.03, 0.075, 0.001, 0.0649),
    ],
    quiet: { feed: 0.025, kill: 0.06 },
    threshold: { feed: 0.055, kill: 0.062 },
    citation: [
      'Pearson, Complex patterns in a simple system',
      'https://doi.org/10.1126/science.261.5118.189',
    ],
  }),
  defineWork({
    slug: 'heat-diffusion',
    title: 'Heat / Diffusion',
    subtitle: 'Difference dissolving into distance',
    gallery: 'matter-pattern',
    runtime: 'field-v1',
    render: 'field',
    kernel: 'heat',
    tier: 'collection',
    year: '1822',
    authors: ['Joseph Fourier'],
    duration: 16,
    summary: 'A smooth periodic temperature field spreads irreversibly toward uniformity.',
    question: 'Why does the future remember less spatial detail than the past?',
    equation: '∂u/∂t = α∇²u',
    parameters: [
      parameter('diffusivity', 'Diffusivity', 'α', 0.03, 1, 0.01, 0.25),
      parameter('sources', 'Initial Fourier modes', 'n', 1, 5, 1, 2),
    ],
    quiet: { diffusivity: 0.08, sources: 1 },
    threshold: { diffusivity: 0.75, sources: 4 },
    citation: [
      'Fourier, Théorie analytique de la chaleur',
      'https://gallica.bnf.fr/ark:/12148/bpt6k1045508v',
    ],
  }),
  defineWork({
    slug: 'schrodinger-wave-packet',
    title: 'Schrödinger Wave Packet',
    subtitle: 'Probability moving as phase',
    gallery: 'matter-pattern',
    runtime: 'field-v1',
    render: 'field',
    kernel: 'schrodinger',
    tier: 'collection',
    year: '1926',
    authors: ['Erwin Schrödinger'],
    duration: 14,
    summary:
      'A localized quantum state travels, interferes, and disperses under unitary evolution.',
    question: 'What does motion mean when position is an amplitude distribution?',
    equation: 'iℏ∂ψ/∂t = −ℏ²∇²ψ/2m (free particle, V=0)',
    parameters: [
      parameter('momentum', 'Momentum', 'k₀', 0.5, 8, 0.1, 3.2),
      parameter('width', 'Packet width', 'σ', 0.2, 2, 0.02, 0.65),
    ],
    quiet: { momentum: 1.2, width: 1.4 },
    threshold: { momentum: 6.5, width: 0.3 },
    citation: [
      'Schrödinger, Quantisierung als Eigenwertproblem',
      'https://doi.org/10.1002/andp.19263840404',
    ],
  }),
  defineWork({
    slug: 'ising-model',
    title: 'Ising Model',
    subtitle: 'A phase transition made of choices',
    gallery: 'matter-pattern',
    runtime: 'discrete-v1',
    render: 'field',
    kernel: 'ising',
    tier: 'collection',
    year: '1925',
    authors: ['Ernst Ising'],
    duration: 32,
    summary: 'Binary spins align locally until a collective magnetic phase appears.',
    question: 'How does a macroscopic phase emerge from nearest-neighbour decisions?',
    equation: 'H = −JΣ⟨ij⟩ sᵢsⱼ − hΣᵢsᵢ',
    parameters: [
      parameter('temperature', 'Temperature', 'T', 0.5, 5, 0.02, 2.27),
      parameter('field', 'External field', 'h', -1, 1, 0.02, 0),
    ],
    quiet: { temperature: 4.2 },
    threshold: { temperature: 2.269 },
    citation: [
      'Ising, Beitrag zur Theorie des Ferromagnetismus',
      'https://doi.org/10.1007/BF02980577',
    ],
  }),
  defineWork({
    slug: 'cahn-hilliard',
    title: 'Cahn–Hilliard Separation',
    subtitle: 'Domains coarsening through conservation',
    gallery: 'matter-pattern',
    runtime: 'field-v1',
    render: 'field',
    kernel: 'cahn-hilliard',
    tier: 'collection',
    year: '1958',
    authors: ['John Cahn', 'John Hilliard'],
    duration: 28,
    summary: 'A mixed material separates into conserved domains whose boundaries slowly simplify.',
    question: 'How can local separation proceed while total composition stays fixed?',
    equation: '∂φ/∂t = M∇²(φ³−φ−κ∇²φ)',
    parameters: [
      parameter('mobility', 'Mobility', 'M', 0.05, 1, 0.01, 0.35),
      parameter('interface', 'Interface cost', 'κ', 0.1, 2, 0.02, 0.7),
    ],
    quiet: { mobility: 0.1, interface: 1.5 },
    threshold: { mobility: 0.8, interface: 0.25 },
    citation: [
      'Cahn & Hilliard, Free Energy of a Nonuniform System I',
      'https://doi.org/10.1063/1.1744102',
    ],
  }),
  defineWork({
    slug: 'lotka-volterra',
    title: 'Lotka–Volterra',
    subtitle: 'A living orbit with no resting point',
    gallery: 'life-reaction',
    runtime: 'ode-v1',
    render: 'phase',
    kernel: 'lotka-volterra',
    tier: 'flagship',
    year: '1925–1926',
    authors: ['Alfred Lotka', 'Vito Volterra'],
    duration: 36,
    summary: 'Predator and prey trace a closed exchange between abundance and scarcity.',
    question: 'How does each population become the other population’s delay?',
    equation: 'ẋ=αx−βxy; ẏ=0.5xy−0.8y',
    parameters: [
      parameter('predation', 'Predation', 'β', 0.1, 2, 0.01, 0.7),
      parameter('recovery', 'Prey growth', 'α', 0.2, 2, 0.01, 1.1),
    ],
    quiet: { predation: 0.25 },
    threshold: { predation: 1.45, recovery: 1.6 },
    citation: [
      'Volterra, Fluctuations in the abundance of a species',
      'https://doi.org/10.1093/icesjms/3.1.3',
    ],
  }),
  defineWork({
    slug: 'brusselator',
    title: 'Brusselator',
    subtitle: 'A chemical clock in two variables',
    gallery: 'life-reaction',
    runtime: 'ode-v1',
    render: 'phase',
    kernel: 'brusselator',
    tier: 'collection',
    year: '1968',
    authors: ['Ilya Prigogine', 'René Lefever'],
    duration: 28,
    summary: 'An open reaction system crosses a Hopf bifurcation into sustained oscillation.',
    question: 'When does a steady chemical state learn to keep time?',
    equation: 'ẋ=A−(B+1)x+x²y; ẏ=Bx−x²y',
    parameters: [
      parameter('a', 'Feed A', 'A', 0.4, 2, 0.02, 1),
      parameter('b', 'Feed B', 'B', 0.5, 5, 0.02, 3),
    ],
    quiet: { b: 1.5 },
    threshold: { b: 2.05 },
    citation: [
      'Prigogine & Lefever, Symmetry breaking instabilities',
      'https://doi.org/10.1063/1.1696890',
    ],
  }),
  defineWork({
    slug: 'oregonator',
    title: 'Oregonator',
    subtitle: 'The pulse inside an oscillating reaction',
    gallery: 'life-reaction',
    runtime: 'ode-v1',
    render: 'phase',
    kernel: 'oregonator',
    tier: 'collection',
    year: '1972',
    authors: ['Richard Field', 'Endre Kőrös', 'Richard Noyes'],
    duration: 30,
    summary: 'A reduced Belousov–Zhabotinsky mechanism produces sharp chemical relaxation cycles.',
    question: 'Why do slow accumulation and fast release form a robust rhythm?',
    equation: 'εẋ=0.02y−xy+x(1−x); ẏ=−0.02y−xy+fz; ż=0.3(x−z)',
    parameters: [
      parameter('epsilon', 'Fast scale', 'ε', 0.02, 0.3, 0.005, 0.08),
      parameter('feedback', 'Feedback', 'f', 0.5, 2.5, 0.02, 1.2),
    ],
    quiet: { epsilon: 0.22 },
    threshold: { epsilon: 0.05, feedback: 1.8 },
    citation: [
      'Field, Kőrös & Noyes, Oscillations in chemical systems II',
      'https://doi.org/10.1021/ja00780a001',
    ],
  }),
  defineWork({
    slug: 'sir-epidemic',
    title: 'SIR Epidemic',
    subtitle: 'An outbreak crossing its own threshold',
    gallery: 'life-reaction',
    runtime: 'ode-v1',
    render: 'series',
    kernel: 'sir',
    tier: 'collection',
    year: '1927',
    authors: ['William Kermack', 'Anderson McKendrick'],
    duration: 80,
    summary:
      'Susceptible, infectious, and removed populations reveal the threshold structure of an epidemic.',
    question: 'When does one introduction become a wave rather than a spark?',
    equation: 'Ṡ=−βSI; İ=βSI−γI; Ṙ=γI',
    parameters: [
      parameter('transmission', 'Transmission', 'β', 0.05, 1, 0.01, 0.34),
      parameter('recovery', 'Recovery', 'γ', 0.03, 0.5, 0.01, 0.12),
    ],
    quiet: { transmission: 0.09 },
    threshold: { transmission: 0.14 },
    citation: [
      'Kermack & McKendrick, A contribution to the mathematical theory of epidemics',
      'https://doi.org/10.1098/rspa.1927.0118',
    ],
  }),
  defineWork({
    slug: 'hodgkin-huxley',
    title: 'Hodgkin–Huxley Neuron',
    subtitle: 'Voltage becoming an event',
    gallery: 'life-reaction',
    runtime: 'ode-v1',
    render: 'series',
    kernel: 'hodgkin-huxley',
    tier: 'collection',
    year: '1952',
    authors: ['Alan Hodgkin', 'Andrew Huxley'],
    duration: 40,
    summary:
      'Voltage-dependent ion gates transform a sustained current into discrete action potentials.',
    question: 'How does continuous current produce all-or-none spikes?',
    equation: 'CᵐV̇=I−g̅ₙₐm³h(V−Eₙₐ)−g̅ₖn⁴(V−Eₖ)−gₗ(V−Eₗ)',
    parameters: [
      parameter('current', 'Applied current', 'I', 0, 30, 0.2, 10),
      parameter('conductance', 'Na conductance', 'gₙₐ', 60, 180, 1, 120),
    ],
    quiet: { current: 2 },
    threshold: { current: 6.3 },
    citation: [
      'Hodgkin & Huxley, A quantitative description of membrane current',
      'https://doi.org/10.1113/jphysiol.1952.sp004764',
    ],
  }),
  defineWork({
    slug: 'fitzhugh-nagumo',
    title: 'FitzHugh–Nagumo',
    subtitle: 'Excitation reduced to its silhouette',
    gallery: 'life-reaction',
    runtime: 'ode-v1',
    render: 'phase',
    kernel: 'fitzhugh-nagumo',
    tier: 'collection',
    year: '1961',
    authors: ['Richard FitzHugh', 'Jin-ichi Nagumo'],
    duration: 36,
    summary:
      'A fast activator and slow recovery variable preserve the geometry of neuronal excitability.',
    question: 'What is the smallest phase portrait that can still spike?',
    equation: 'v̇=v−v³/3−w+I; τẇ=v+a−bw',
    parameters: [
      parameter('current', 'Drive', 'I', 0, 1.2, 0.01, 0.48),
      parameter('recovery', 'Recovery rate', 'τ⁻¹', 0.02, 0.3, 0.005, 0.08),
    ],
    quiet: { current: 0.18 },
    threshold: { current: 0.34 },
    citation: [
      'FitzHugh, Impulses and physiological states in theoretical models of nerve membrane',
      'https://doi.org/10.1016/S0006-3495(61)86902-6',
    ],
  }),
  defineWork({
    slug: 'lorenz-atmosphere',
    title: 'Lorenz Atmosphere',
    subtitle: 'Weather on a butterfly-shaped set',
    gallery: 'earth-climate',
    runtime: 'ode-v1',
    render: 'phase',
    kernel: 'lorenz',
    tier: 'flagship',
    year: '1963',
    authors: ['Edward Lorenz'],
    duration: 38,
    summary:
      'Three variables abstract atmospheric convection into a bounded but unpredictable attractor.',
    question: 'How can deterministic weather lose its forecast?',
    equation: 'ẋ=σ(y−x); ẏ=x(ρ−z)−y; ż=xy−βz',
    parameters: [
      parameter('rho', 'Thermal forcing', 'ρ', 0, 50, 0.1, 28),
      parameter('sigma', 'Prandtl number', 'σ', 1, 20, 0.1, 10),
    ],
    quiet: { rho: 12 },
    threshold: { rho: 24.74 },
    citation: [
      'Lorenz, Deterministic Nonperiodic Flow',
      'https://doi.org/10.1175/1520-0469(1963)020%3C0130:DNF%3E2.0.CO;2',
    ],
  }),
  defineWork({
    slug: 'stommel-box',
    title: 'Stommel Ocean Box',
    subtitle: 'Two stable oceans under one climate',
    gallery: 'earth-climate',
    runtime: 'ode-v1',
    render: 'phase',
    kernel: 'stommel',
    tier: 'collection',
    year: '1961',
    authors: ['Henry Stommel'],
    duration: 60,
    summary:
      'Temperature and salinity feedbacks permit abrupt switches in overturning circulation.',
    question: 'How can the same forcing support two different oceans?',
    equation: 'q=k(T−S); Ṫ=1−T−|q|T; Ṡ=F−S−|q|S',
    parameters: [
      parameter('freshwater', 'Freshwater forcing', 'F', 0, 2, 0.01, 0.85),
      parameter('exchange', 'Exchange', 'k', 0.1, 2, 0.02, 0.7),
    ],
    quiet: { freshwater: 0.25 },
    threshold: { freshwater: 1.2 },
    citation: [
      'Stommel, Thermohaline convection with two stable regimes',
      'https://doi.org/10.1111/j.2153-3490.1961.tb00079.x',
    ],
  }),
  defineWork({
    slug: 'daisyworld',
    title: 'Daisyworld',
    subtitle: 'Life bending a planet’s thermostat',
    gallery: 'earth-climate',
    runtime: 'ode-v1',
    render: 'series',
    kernel: 'daisyworld',
    tier: 'collection',
    year: '1983',
    authors: ['James Lovelock', 'Andrew Watson'],
    duration: 50,
    summary:
      'Dark and light daisies alter albedo, coupling ecological competition to planetary temperature.',
    question: 'Can selection create regulation without planning it?',
    equation: 'ẋᵢ=xᵢ[β₊(Tᵢ)(1−Σx)−γ], with β₊=max(0,β)',
    parameters: [
      parameter('luminosity', 'Solar luminosity', 'L', 0.6, 1.6, 0.01, 1),
      parameter('death', 'Mortality', 'γ', 0.1, 0.6, 0.01, 0.3),
    ],
    quiet: { luminosity: 0.72 },
    threshold: { luminosity: 1.35 },
    citation: [
      'Watson & Lovelock, Biological homeostasis of the global environment',
      'https://doi.org/10.1111/j.1600-0889.1983.tb00031.x',
    ],
  }),
  defineWork({
    slug: 'carbon-cycle',
    title: 'Three-Box Carbon Cycle',
    subtitle: 'Carbon moving between timescales',
    gallery: 'earth-climate',
    runtime: 'ode-v1',
    render: 'series',
    kernel: 'carbon-cycle',
    tier: 'collection',
    year: '1957',
    authors: ['Roger Revelle', 'Hans Suess'],
    duration: 120,
    summary:
      'A finite emission pulse is redistributed among atmosphere, ocean, and biosphere reservoirs.',
    question: 'Why does a pulse persist after its source stops?',
    equation: 'Ċₐ=E(t)−kₐₒCₐ+kₒₐCₒ−kₐᵇCₐ+kᵇₐCᵇ; E(t)=E for t<0.22T, else 0',
    parameters: [
      parameter('emission', 'Emission pulse', 'E', 0, 5, 0.05, 1.8),
      parameter('ocean', 'Ocean uptake', 'kₐₒ', 0.01, 0.5, 0.01, 0.12),
    ],
    quiet: { emission: 0.4 },
    threshold: { emission: 4.2, ocean: 0.05 },
    citation: [
      'Revelle & Suess, Carbon dioxide exchange between atmosphere and ocean',
      'https://doi.org/10.1111/j.2153-3490.1957.tb01849.x',
    ],
  }),
  defineWork({
    slug: 'shallow-water',
    title: 'Shallow-Water Waves',
    subtitle: 'An ocean compressed into a moving surface',
    gallery: 'earth-climate',
    runtime: 'field-v1',
    render: 'field',
    kernel: 'shallow-water',
    tier: 'collection',
    year: '1776',
    authors: ['Pierre-Simon Laplace'],
    duration: 20,
    summary:
      'Linearized depth-averaged conservation laws carry rotating gravity waves across a periodic surface.',
    question: 'What structure survives when a three-dimensional ocean becomes a sheet?',
    equation: '∂ₜη=−H∇·u; ∂ₜ u=−g∂ₓη+fv; ∂ₜ v=−g∂ᵧη−fu',
    parameters: [
      parameter('depth', 'Mean depth', 'H', 0.2, 2, 0.02, 1),
      parameter('rotation', 'Rotation', 'f', 0, 2, 0.02, 0.7),
    ],
    quiet: { depth: 0.4, rotation: 0.2 },
    threshold: { depth: 1.7, rotation: 1.6 },
    citation: [
      'Vallis, Atmospheric and Oceanic Fluid Dynamics',
      'https://doi.org/10.1017/9781107588417',
    ],
  }),
  defineWork({
    slug: 'budyko-sellers',
    title: 'Budyko–Sellers Climate',
    subtitle: 'An ice line with a memory',
    gallery: 'earth-climate',
    runtime: 'field-v1',
    render: 'field',
    kernel: 'budyko-sellers',
    tier: 'collection',
    year: '1969',
    authors: ['Mikhail Budyko', 'William Sellers'],
    duration: 70,
    summary:
      'Latitudinal energy balance and ice–albedo feedback create warm and snowball equilibria.',
    question: 'How can a moving ice edge turn gradual forcing into a jump?',
    equation: 'C∂ₜT=Q(1−α(T))−(A+BT)+D∇²T',
    parameters: [
      parameter('solar', 'Solar forcing', 'Q', 0.7, 1.3, 0.01, 1),
      parameter('transport', 'Heat transport', 'D', 0.05, 1, 0.01, 0.35),
    ],
    quiet: { solar: 1.15 },
    threshold: { solar: 0.88 },
    citation: [
      'Budyko, The effect of solar radiation variations on the climate of the Earth',
      'https://doi.org/10.1111/j.2153-3490.1969.tb00466.x',
    ],
  }),
  defineWork({
    slug: 'restricted-three-body',
    title: 'Restricted Three-Body',
    subtitle: 'A small body inside two gravities',
    gallery: 'cosmos-gravity',
    runtime: 'ode-v1',
    render: 'orbit',
    kernel: 'restricted-three-body',
    tier: 'flagship',
    year: '1772',
    authors: ['Joseph-Louis Lagrange'],
    duration: 34,
    summary: 'A negligible third mass moves through a rotating landscape shaped by two primaries.',
    question: 'Where can motion remain bounded when no single center owns the orbit?',
    equation: 'ẍ−2ẏ=∂Ω/∂x; ÿ+2ẋ=∂Ω/∂y',
    parameters: [
      parameter('massRatio', 'Mass ratio', 'μ', 0.001, 0.49, 0.001, 0.012),
      parameter('velocity', 'Initial velocity', 'v₀', 0.1, 1.5, 0.01, 0.62),
    ],
    quiet: { velocity: 0.35 },
    threshold: { velocity: 1.08 },
    citation: ['Szebehely, Theory of Orbits', 'https://doi.org/10.1016/B978-0-12-395732-0.X5001-6'],
  }),
  defineWork({
    slug: 'kepler-orbit',
    title: 'Kepler Orbit',
    subtitle: 'Equal areas, unequal speeds',
    gallery: 'cosmos-gravity',
    runtime: 'analytic-v1',
    render: 'orbit',
    kernel: 'kepler',
    tier: 'collection',
    year: '1609',
    authors: ['Johannes Kepler'],
    duration: 24,
    summary: 'A planet traces an ellipse while its radius sweeps equal areas in equal times.',
    question: 'How does one conserved angular momentum organize an entire orbit?',
    equation: 'r(θ)=a(1−e²)/(1+e cosθ)',
    parameters: [
      parameter('eccentricity', 'Eccentricity', 'e', 0, 0.92, 0.01, 0.48),
      parameter('axis', 'Semi-major axis', 'a', 0.5, 2, 0.02, 1),
    ],
    quiet: { eccentricity: 0.08 },
    threshold: { eccentricity: 0.86 },
    citation: ['Kepler, Astronomia Nova', 'https://doi.org/10.5479/sil.126675.39088002685477'],
  }),
  defineWork({
    slug: 'hohmann-transfer',
    title: 'Hohmann Transfer',
    subtitle: 'The quiet economy of two burns',
    gallery: 'cosmos-gravity',
    runtime: 'analytic-v1',
    render: 'orbit',
    kernel: 'hohmann',
    tier: 'collection',
    year: '1925',
    authors: ['Walter Hohmann'],
    duration: 18,
    summary: 'Two impulsive velocity changes connect circular orbits through one tangent ellipse.',
    question: 'Why can the slowest-looking path require the least velocity change?',
    equation: 'Δv₁=√(μ/r₁)[√(2r₂/(r₁+r₂))−1]',
    parameters: [
      parameter('target', 'Target radius', 'r₂/r₁', 1.2, 6, 0.02, 2.2),
      parameter('phase', 'Departure phase', 'φ', 0, 6.28, 0.02, 0),
    ],
    quiet: { target: 1.35 },
    threshold: { target: 4.8 },
    citation: [
      'Hohmann, Die Erreichbarkeit der Himmelskörper',
      'https://ntrs.nasa.gov/citations/19900010455',
    ],
  }),
  defineWork({
    slug: 'n-body-system',
    title: 'N-Body System',
    subtitle: 'Gravity writing with several hands',
    gallery: 'cosmos-gravity',
    runtime: 'ode-v1',
    render: 'orbit',
    kernel: 'n-body',
    tier: 'collection',
    year: '1687',
    authors: ['Isaac Newton'],
    duration: 32,
    summary:
      'Three gravitating masses exchange energy and momentum without a closed general solution.',
    question: 'What remains conserved while every orbit reshapes every other?',
    equation: 'r̈ᵢ=GΣⱼ≠ᵢmⱼ(rⱼ−rᵢ)/(|rⱼ−rᵢ|²+ε²)³ᐟ²; ε=0.12',
    parameters: [
      parameter('mass', 'Third mass', 'm₃', 0.05, 2, 0.01, 0.6),
      parameter('velocity', 'Orbital speed', 'v', 0.2, 1.8, 0.01, 0.82),
    ],
    quiet: { mass: 0.08 },
    threshold: { mass: 1.5, velocity: 1.2 },
    citation: [
      'Newton, Philosophiae Naturalis Principia Mathematica',
      'https://doi.org/10.5479/sil.52126.39088015628399',
    ],
  }),
  defineWork({
    slug: 'friedmann-lemaitre',
    title: 'Friedmann–Lemaître Universe',
    subtitle: 'The scale of space becoming time',
    gallery: 'cosmos-gravity',
    runtime: 'ode-v1',
    render: 'series',
    kernel: 'friedmann',
    tier: 'collection',
    year: '1922–1927',
    authors: ['Alexander Friedmann', 'Georges Lemaître'],
    duration: 24,
    summary:
      'Matter, curvature, and vacuum energy determine the expansion history of a homogeneous universe.',
    question: 'How does the inventory of the cosmos decide its geometry in time?',
    equation: 'H²/H₀²=Ωᵣa⁻³+Ωₖa⁻²+ΩΛ',
    parameters: [
      parameter('matter', 'Matter density', 'Ωᵣ', 0.05, 1.5, 0.01, 0.3),
      parameter('vacuum', 'Vacuum density', 'ΩΛ', 0, 1.5, 0.01, 0.7),
    ],
    quiet: { matter: 1, vacuum: 0 },
    threshold: { matter: 0.08, vacuum: 1.15 },
    citation: [
      'Lemaître, A homogeneous universe of constant mass and increasing radius',
      'https://ui.adsabs.harvard.edu/abs/1927ASSB...47...49L',
    ],
  }),
  defineWork({
    slug: 'exoplanet-transit',
    title: 'Exoplanet Transit',
    subtitle: 'A distant world measured as missing light',
    gallery: 'cosmos-gravity',
    runtime: 'analytic-v1',
    render: 'series',
    kernel: 'exoplanet-transit',
    tier: 'collection',
    year: '1999',
    authors: ['David Charbonneau', 'Timothy Brown'],
    duration: 16,
    summary:
      'A planet crossing its star produces a symmetric, geometry-dependent dip in observed brightness.',
    question: 'How much can a shadow reveal about a world that cannot be resolved?',
    equation: 'F=1−A_overlap/(πR⋆²) for two uniform projected disks',
    parameters: [
      parameter('radius', 'Radius ratio', 'Rₚ/R⋆', 0.02, 0.25, 0.002, 0.1),
      parameter('impact', 'Impact parameter', 'b', 0, 1.2, 0.01, 0.35),
    ],
    quiet: { radius: 0.04, impact: 0.1 },
    threshold: { radius: 0.2, impact: 0.95 },
    citation: [
      'Charbonneau et al., Detection of Planetary Transits Across a Sun-like Star',
      'https://doi.org/10.1086/312457',
    ],
  }),
];

const communityModules = import.meta.glob<unknown>('../works/community/*.json', {
  eager: true,
  import: 'default',
});

const communityWorks: WorkManifestV2[] = parseCommunityManifestCollection(
  Object.entries(communityModules).map(([source, manifest]) => ({ source, manifest })),
).map((work) => {
  if (work.schemaVersion === 2) {
    assertValidPortraitExtension(work.portrait);
    return work;
  }
  const portrait = createPortraitExtension({
    slug: work.slug,
    kernel: work.kernel,
    render: work.render,
    parameters: work.parameters,
    presets: work.presets,
  });
  assertValidPortraitExtension(portrait);
  return { ...work, schemaVersion: 2, portrait };
});

export const works: WorkManifest[] = [...builtInWorks, ...communityWorks];

const minimumCount = 30;
if (builtInWorks.length !== minimumCount || works.length < minimumCount) {
  throw new Error(
    `DynaMusium catalog must contain at least ${minimumCount} works; found ${works.length}.`,
  );
}

if (new Set(works.map((work) => work.slug)).size !== works.length) {
  throw new Error('DynaMusium catalog contains a duplicate work slug.');
}

export const workBySlug = new Map(works.map((work) => [work.slug, work]));
